# Nombre de la aplicación
spring.application.name=glicem_ia_test

# Configuración de base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:glicemia_db_test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Prefijos de vistas JSP
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

# Habilitar métodos ocultos en formularios
spring.mvc.hiddenmethod.filter.enabled=true

# API key falsa solo para entorno de pruebas
gemini.api.key=AIzaSyDCRqzR4sktXzJNOCzpCXUHj-9nZ-PUqjw
